services:
    dev:
        image: golang:1.23
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        environment:
            MONGO_CONNECTION_STRING: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
        networks:
            - redditminer

    mongo:
        image: mongo
        restart: always
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        networks:
            - redditminer

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - ${MONGO_PORT_UI}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        networks:
            - redditminer

networks:
    redditminer:
        external: true
